<a href="https://colab.research.google.com/github/swopnimghimire-123123/Machine-Learning-Journey/blob/main/10_Introduction_To_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

Tensors are fundamental building blocks in many areas of mathematics, physics, and especially in modern machine learning and deep learning frameworks like TensorFlow and PyTorch. At their core, tensors are generalizations of scalars, vectors, and matrices.

## What is a Tensor?

*   **Scalar:** A single number (e.g., 5, -3.14). This is a 0th-order tensor.
*   **Vector:** An array of numbers (e.g., [1, 2, 3]). This is a 1st-order tensor.
*   **Matrix:** A 2D array of numbers (e.g., [[1, 2], [3, 4]]). This is a 2nd-order tensor.
*   **Tensor:** An n-dimensional array of numbers. This is an n-th order tensor.

Think of a tensor as a container that can hold data in a structured way, with different levels of complexity based on its "order" or "rank".

## Properties of Tensors

1.  **Order/Rank:** The number of dimensions a tensor has. A scalar has rank 0, a vector has rank 1, a matrix has rank 2, and so on.
2.  **Shape:** A tuple of integers describing the size of each dimension. For example, a matrix with 3 rows and 4 columns has a shape of (3, 4). A tensor with shape (2, 3, 4) has 2 "layers", each with 3 rows and 4 columns.
3.  **Data Type:** The type of data stored in the tensor (e.g., integer, float, boolean).

## Why are Tensors Important?

*   **Representing Data:** Tensors are a natural way to represent many types of data used in machine learning, such as images (height x width x color channels), videos (frames x height x width x color channels), and text (sequences x embeddings).
*   **Mathematical Operations:** Many mathematical operations commonly used in machine learning (like matrix multiplication, element-wise operations, and reductions) are defined for tensors. Deep learning models are essentially complex networks of tensor operations.
*   **Hardware Acceleration:** Frameworks like TensorFlow and PyTorch are designed to efficiently perform tensor operations on specialized hardware like GPUs (Graphics Processing Units) and TPUs (Tensor Processing Units), which are crucial for training large neural networks.

## Tensor Operations

Just like you can perform operations on scalars, vectors, and matrices, you can perform operations on tensors. Some common operations include:

*   **Addition and Subtraction:** Element-wise operations.
*   **Multiplication:** Element-wise multiplication or matrix multiplication (for tensors of appropriate shapes).
*   **Broadcasting:** A mechanism that allows operations between tensors of different shapes under certain conditions.
*   **Reshaping:** Changing the shape of a tensor without changing its data.
*   **Slicing and Indexing:** Accessing specific elements or sub-tensors.

## Tensors in Deep Learning Frameworks

In deep learning frameworks, tensors are often represented as objects with methods for performing these operations. These frameworks provide optimized implementations of tensor operations, often leveraging hardware acceleration.

For example, in PyTorch or TensorFlow, you might create a tensor like this:

## Rank, Axes, and Shape Explained

Let's delve deeper into the concepts of rank, axes, and shape:

*   **Rank (or Order or Degree):** This is the number of dimensions in the tensor.
    *   A scalar has a rank of 0.
    *   A vector has a rank of 1.
    *   A matrix has a rank of 2.
    *   A tensor with 3 dimensions has a rank of 3, and so on.
    The rank tells you how many indices you need to access a specific element in the tensor.

*   **Axes (or Dimensions):** Each dimension of a tensor is called an axis. Tensors are indexed along their axes.
    *   A vector has one axis.
    *   A matrix has two axes (typically rows and columns).
    *   A 3D tensor has three axes.
    The axes are ordered, and we refer to them by their integer index, starting from 0. So, for a 3D tensor, axis 0 might represent layers, axis 1 rows, and axis 2 columns.

*   **Shape:** This is a tuple of integers that describes the size of the tensor along each axis. The length of the shape tuple is equal to the rank of the tensor.
    *   A scalar has an empty shape `()`.
    *   A vector with 5 elements has a shape `(5,)`.
    *   A matrix with 3 rows and 4 columns has a shape `(3, 4)`.
    *   A 3D tensor with 2 layers, 3 rows, and 4 columns has a shape `(2, 3, 4)`.
    The shape tells you the number of elements along each dimension of the tensor.

In essence, the rank tells you *how many* dimensions there are, the axes refer to the *individual dimensions* that you can index along, and the shape tells you the *size* of each of those dimensions.

In [ ]:
import tensorflow as tf

# 0D Tensor (Scalar)
scalar = tf.constant(5)
print("0D Tensor (Scalar):")
print(scalar)
print("Shape:", scalar.shape)
print("Rank:", tf.rank(scalar).numpy())
print("-" * 20)

# 1D Tensor (Vector)
vector = tf.constant([1, 2, 3, 4])
print("1D Tensor (Vector):")
print(vector)
print("Shape:", vector.shape)
print("Rank:", tf.rank(vector).numpy())
print("-" * 20)

# 2D Tensor (Matrix)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):")
print(matrix)
print("Shape:", matrix.shape)
print("Rank:", tf.rank(matrix).numpy())
print("-" * 20)

# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)
print("Rank:", tf.rank(tensor_3d).numpy())
print("-" * 20)

# 4D Tensor (example: a batch of images, batch_size x height x width x channels)
tensor_4d = tf.constant([
    [[[1, 1], [2, 2]], [[3, 3], [4, 4]]],
    [[[5, 5], [6, 6]], [[7, 7], [8, 8]]]
])
print("4D Tensor:")
print(tensor_4d)
print("Shape:", tensor_4d.shape)
print("Rank:", tf.rank(tensor_4d).numpy())
print("-" * 20)

# 5D Tensor (example: a batch of video frames, batch_size x frames x height x width x channels)
tensor_5d = tf.constant([
    [[[[[1], [2]], [[3], [4]]]], [[[[5], [6]], [[7], [8]]]]]
])
print("5D Tensor:")
print(tensor_5d)
print("Shape:", tensor_5d.shape)
print("Rank:", tf.rank(tensor_5d).numpy())
print("-" * 20)

0D Tensor (Scalar):
tf.Tensor(5, shape=(), dtype=int32)
Shape: ()
Rank: 0
--------------------
1D Tensor (Vector):
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Shape: (4,)
Rank: 1
--------------------
2D Tensor (Matrix):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Rank: 2
--------------------
3D Tensor:
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)
Rank: 3
--------------------
4D Tensor:
tf.Tensor(
[[[[1 1]
   [2 2]]

  [[3 3]
   [4 4]]]


 [[[5 5]
   [6 6]]

  [[7 7]
   [8 8]]]], shape=(2, 2, 2, 2), dtype=int32)
Shape: (2, 2, 2, 2)
Rank: 4
--------------------
5D Tensor:
tf.Tensor(
[[[[[[1]
     [2]]

    [[3]
     [4]]]]



  [[[[5]
     [6]]

    [[7]
     [8]]]]]], shape=(1, 2, 1, 2, 2, 1), dtype=int32)
Shape: (1, 2, 1, 2, 2, 1)
Rank: 6
--------------------


Let's illustrate tensors of different dimensions with examples:

*   **0D Tensor (Scalar):** A single number.