<a href="https://colab.research.google.com/github/swopnimghimire-123123/Machine-Learning-Journey/blob/main/50.2_MLR_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mathematical Formation of Multiple Linear Regression from Scratch

Multiple linear regression is a statistical technique used to model the relationship between a dependent variable and two or more independent variables. It extends the concept of simple linear regression to accommodate multiple predictors.

**1. The Model Equation:**

In multiple linear regression, the relationship between the dependent variable (often denoted as $y$) and the independent variables (denoted as $x_1, x_2, \dots, x_n$) is modeled as a linear equation:

$y = \beta_0 + \beta_1x_1 + \beta_2x_2 + \dots + \beta_nx_n + \epsilon$

Where:
*   $y$ is the dependent variable (the variable we are trying to predict).
*   $x_1, x_2, \dots, x_n$ are the independent variables (the predictors).
*   $\beta_0$ is the intercept (the value of $y$ when all independent variables are zero).
*   $\beta_1, \beta_2, \dots, \beta_n$ are the coefficients for each independent variable. These coefficients represent the change in $y$ for a one-unit change in the corresponding independent variable, holding all other independent variables constant.
*   $\epsilon$ is the error term (also known as the residual). This represents the part of $y$ that cannot be explained by the linear relationship with the independent variables. It is assumed to be random and follow a normal distribution with a mean of zero.

**2. Matrix Notation:**

For ease of calculation and understanding, the multiple linear regression model can be expressed in matrix notation:

$Y = X\beta + \epsilon$

Where:
*   $Y$ is a column vector of the dependent variable observations ($m \times 1$, where $m$ is the number of observations).
$Y = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_m \end{bmatrix}$

*   $X$ is the design matrix, which contains the values of the independent variables for each observation. It also includes a column of ones for the intercept term ($m \times (n+1)$).
$X = \begin{bmatrix} 1 & x_{11} & x_{12} & \dots & x_{1n} \\ 1 & x_{21} & x_{22} & \dots & x_{2n} \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 1 & x_{m1} & x_{m2} & \dots & x_{mn} \end{bmatrix}$

*   $\beta$ is a column vector of the coefficients, including the intercept ($\,(n+1) \times 1$).
$\beta = \begin{bmatrix} \beta_0 \\ \beta_1 \\ \vdots \\ \beta_n \end{bmatrix}$

*   $\epsilon$ is a column vector of the error terms for each observation ($m \times 1$).
$\epsilon = \begin{bmatrix} \epsilon_1 \\ \epsilon_2 \\ \vdots \\ \epsilon_m \end{bmatrix}$

**3. Estimating the Coefficients (Ordinary Least Squares - OLS):**

The goal of multiple linear regression is to find the values of the coefficients ($\beta$) that best fit the data. The most common method for estimating these coefficients is Ordinary Least Squares (OLS). OLS aims to minimize the sum of the squared differences between the observed values of $y$ and the values predicted by the model. This sum of squared differences is called the Residual Sum of Squares (RSS) or Sum of Squared Errors (SSE).

The predicted value of $y$ for an observation is denoted as $\hat{y}$, and is given by:

$\hat{y} = \beta_0 + \beta_1x_1 + \beta_2x_2 + \dots + \beta_nx_n$

In matrix notation, the vector of predicted values is:

$\hat{Y} = X\hat{\beta}$

The error for each observation is $e_i = y_i - \hat{y}_i$, and the vector of errors is $e = Y - \hat{Y}$.

The RSS is calculated as the sum of the squared errors:

$RSS = \sum_{i=1}^m (y_i - \hat{y}_i)^2 = \sum_{i=1}^m e_i^2$

In matrix notation, the RSS is:

$RSS = e^Te = (Y - X\hat{\beta})^T(Y - X\hat{\beta})$

To find the values of $\hat{\beta}$ that minimize the RSS, we take the derivative of the RSS with respect to $\hat{\beta}$ and set it to zero. This involves matrix calculus. The steps are as follows:

$RSS = Y^TY - Y^TX\hat{\beta} - (X\hat{\beta})^TY + (X\hat{\beta})^TX\hat{\beta}$
$RSS = Y^TY - Y^TX\hat{\beta} - \hat{\beta}^TX^TY + \hat{\beta}^TX^TX\hat{\beta}$

Since $Y^TX\hat{\beta}$ is a scalar, its transpose is itself: $(Y^TX\hat{\beta})^T = \hat{\beta}^TX^TY$. So,

$RSS = Y^TY - 2\hat{\beta}^TX^TY + \hat{\beta}^TX^TX\hat{\beta}$

Now, taking the derivative with respect to $\hat{\beta}$:

$\frac{\partial RSS}{\partial \hat{\beta}} = -2X^TY + 2X^TX\hat{\beta}$

Setting the derivative to zero to find the minimum:

$-2X^TY + 2X^TX\hat{\beta} = 0$
$2X^TX\hat{\beta} = 2X^TY$
$X^TX\hat{\beta} = X^TY$

Assuming that $(X^TX)$ is invertible (which is usually the case when there is no perfect multicollinearity), we can solve for $\hat{\beta}$:

$\hat{\beta} = (X^TX)^{-1}X^TY$

This is the formula for the OLS estimators of the coefficients in multiple linear regression.

**4. Assumptions of Multiple Linear Regression:**

For the OLS estimators to be the Best Linear Unbiased Estimators (BLUE), several assumptions must be met:

*   **Linearity:** The relationship between the dependent variable and the independent variables is linear.
*   **Independence of Errors:** The errors are independent of each other.
*   **Homoscedasticity:** The variance of the errors is constant across all levels of the independent variables.
*   **Normality of Errors:** The errors are normally distributed.
*   **No Multicollinearity:** The independent variables are not perfectly linearly correlated with each other.

**In summary, the mathematical formation of multiple linear regression involves defining a linear model equation, representing it in matrix notation, and using the OLS method to estimate the coefficients by minimizing the sum of squared errors. The formula $\hat{\beta} = (X^TX)^{-1}X^TY$ provides the estimated coefficients based on the observed data.**

In [2]:
import numpy as np
from sklearn.datasets import load_diabetes

In [3]:

X,y = load_diabetes(return_X_y=True)

In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
X.shape , y.shape

((442, 10), (442,))

### Using Sklearn's Linear Regression

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
reg = LinearRegression()

In [11]:
reg.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred = reg.predict(X_test)

In [14]:
from sklearn.metrics import r2_score

In [15]:
r2_score(y_test, y_pred)

0.4399338661568968

In [17]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [19]:
reg.intercept_

np.float64(151.88331005254167)

### Making our own Linear Regression Class

In [23]:
class MyLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [24]:
lr = MyLR()

In [25]:
lr.fit(X_train, y_train)

In [27]:
X_train.shape

(353, 10)

In [28]:
np.insert(X_train, 0 , 1, axis = 1).shape

(353, 11)

In [30]:

y_pred = lr.predict(X_test)

In [31]:

r2_score(y_test,y_pred)

0.43993386615689634

In [32]:
lr.coef_, lr.intercept_

(array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]),
 np.float64(151.88331005254165))